---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/11/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql-11

    - name: "Take Overall DB Backup"
      shell: "pg_dump -U postgres -F t {{db_name}} > {{backup_location}}"

    - name: "Backup The Transaction Log"
      shell: "cp /var/lib/pgsql/11/data/pg_log/postgresql-{{log_date}}.csv {{transaction_log_backup_location}}" 

    - name: "DB Creation For Restore DB Backup"
      shell: "createdb -U postgres '{{clone_db_name}}'"
      register: create_clone_db

    - name: "Restore the DB Backup"
      shell: "pg_restore -U postgres -d '{{clone_db_name}}' '{{backup_location}}'"

  handlers:
    - name: restart postgres
      service: name=postgresql-11 state=restarted
      